feat(mom): freePath now with number reusability config

diff --git a/bin/mom b/bin/mom
--- a/bin/mom
+++ b/bin/mom
@@ -6,17 +6,20 @@ SSS_OPTS[about]='MOM - Media Operation/Manipulation
 A collection of media operation/manipulation scripts.'
 
 ((SCRIPT_OPTS[jobs] = (1 + $(nproc --all)) / 2))
+SCRIPT_OPTS[freePathNumberReuse]=0
 SCRIPT_OPTS[ffmpegSetLogLevel]=2
 defineParams=(
-	jobs 'j?' '[0-9]*' "Number of jobs to run in parallel (default=${SCRIPT_OPTS[jobs]})"
-	ffmpegSetLogLevel 'f?' '' 'Change ffmpeg log level to current script value'
+	jobs 'j?' '[0-9]*' "Number of jobs to run in parallel (default=${SCRIPT_OPTS['jobs']})"
+	freePathNumberReuse 'n?' '' 'Increment numbers in paths without appending (default=0)'
+	ffmpegSetLogLevel 'f?' '-?[0-9]*' "Change ffmpeg log level to current script value\
+ (<0 for setting a specific level)"
 	"${defineParams[@]}")
 SSS_OPTS[onNoArg]=1
 
 ffmpegCmd() {
-	((SCRIPT_OPTS[ffmpegSetLogLevel] > 0)) &&
-		echo ffmpeg -v ${LOG_NAMES[${SCRIPT_OPTS[logLvl]}]/warn/warning} ||
-		echo ffmpeg -v ${LOG_NAMES[$((-SCRIPT_OPTS[ffmpegSetLogLevel]))]/warn/warning}
+	((SCRIPT_OPTS['ffmpegSetLogLevel'] > 0)) &&
+		echo ffmpeg -v ${LOG_NAMES[${SCRIPT_OPTS['logLvl']}]/warn/warning} ||
+		echo ffmpeg -v ${LOG_NAMES[$((-SCRIPT_OPTS['ffmpegSetLogLevel']))]/warn/warning}
 }
 
 actionInfo download 'download audio/video from given url with `yt-dlp`'
@@ -38,7 +41,7 @@ download() { # TODO: allow video; allow qual/fmt selection through a picker
 		function isolated() {
 			local prefix=$prefix-${src#*=}-
 			local cmd=("${cmd[@]}" "$src" -o "$prefix$tmp") dst=${dst[i]:-$dst}
-			((SCRIPT_OPTS[logLvl] < 3)) && cmd+=(-q)
+			((SCRIPT_OPTS['logLvl'] < 3)) && cmd+=(-q)
 			exec "${cmd[@]}" && {
 				cmd=("$prefix"*)
 				ffprobe "$cmd" |& grep 'Audio: aac' -q && local ext=m4a || local ext=opus
@@ -76,7 +79,7 @@ noMeta() {
 	else
 		[[ ${dst:-$src} == "$src" ]] && local dst=/tmp replaceSrc=$((1 - keep))
 
-		[[ -d $dst ]] && local dst=$(getFreePath "${dst%/}/${src##*/}" dst)
+		[[ -d $dst ]] && local dst=$(ACTION+=.dst getFreePath "${dst%/}/${src##*/}")
 		local cmd=($(ffmpegCmd) -i "$src" -map_metadata -1 -map a -c copy "$dst")
 		exec "${cmd[@]}" && if ((replaceSrc > 0)); then
 			exec mv "$dst" "$src"
@@ -119,7 +122,7 @@ lua
 	declare -n arr=$1
 	local _opts=(--msg-level=cplayer=error --no-audio-display --loop-playlist --display-tags-clr
 		--term-playing-msg="$(print "<Enter> to pick --$1") time for $(
-			((SCRIPT_OPTS[color] > 0)) && ansi italic "'\${media-title}'" reset || echo '${media-title}'
+			((SCRIPT_OPTS['color'] > 0)) && ansi italic "'\${media-title}'" reset || echo '${media-title}'
 		)" --script="$pickerFile")
 	local msg=
 	for src in "${src[@]:${#arr[@]}}"; do
@@ -158,29 +161,42 @@ secondsToTime() {
 }
 
 # $src, $2= name of the param for which we are creating the path
+#######################################
+# Globals:
+#   keepOriginal if the original will not be replaced by this path
+#   src source filename (if dst should move into it, log path as verbose only)
+# Arguments:
+#   filename base path name to get a free name for
+#######################################
 getFreePath() {
 	if [[ ! -e $1 ]]; then
 		echo "$1"
 		return
 	fi
-	[[ $1 =~ ([0-9]*)(\.[^.]+)$ ]]
-	local name=${1::-${#BASH_REMATCH[0]}} ext=${BASH_REMATCH[2]} numLen=${#BASH_REMATCH[1]}
-	declare -i n=${BASH_REMATCH[1]##0}+1
-	declare -i added=$((numLen - ${#n})) i=added
-	while ((i-- > 0)); do
-		name+=0
-	done
-	[[ ${BASH_REMATCH[1]} ]] || name+=_
-	while [[ -e $name$n$ext ]]; do
-		if ((++n && added > 0 && ${#n} >= numLen)); then
-			name=${name::-$added}
-			unset added
-		fi
-	done
-	local text="$name$n$ext"
-	[[ $1 == "$text" || $1 == "$src" && $keepOriginal -lt 1 ]] &&
-		log Info ".$2 = '$text'" ||
-		log Warn ".$2 = '$text'"
+	local filename=$1 text=$1
+	[[ $filename =~ (0*([1-9][0-9]*)?)(\.[^.]+)$ ]]
+	local ext=${BASH_REMATCH[3]} numLen=${#BASH_REMATCH[1]}
+	if ((${SCRIPT_OPTS['freePathNumberReuse']} > 0 && numLen)); then # num reuse allowed and possible
+		local prefix=${filename::-${#BASH_REMATCH[0]}}
+		declare -i i=${BASH_REMATCH[2]}
+
+		while [[ -e $text ]]; do
+			text=$(printf '%s%0*d%s' "$prefix" $numLen $((++i)) "$ext")
+		done
+	else
+		local prefix=${filename::-${#ext}}_
+		declare -i i=0
+		while [[ -e $text ]]; do
+			text="$prefix$((++i))$ext"
+		done
+	fi
+
+	if [[ $src =~ ^"$prefix"(0*([1-9][0-9]*)?)"$ext"$ &&
+		$keepOriginal -lt 1 && ${BASH_REMATCH[2]} -lt $i ]]; then
+		text=$src # index of src was the lowest number already
+	else
+		log Warn " = '$text'"
+	fi
 	echo "$text"
 }
 
@@ -190,12 +206,12 @@ genDstFromSrc() {
 	local out=${dst:-$src}
 	[[ -d $dst ]] && out="$dst/${src##*/}"
 	# default path included to not override source file, but override if file dst was given
-	[[ -d ${dst:-.} ]] && out=$(getFreePath "$out" dst)
+	[[ -d ${dst:-.} ]] && out=$(ACTION+=.dst getFreePath "$out")
 	echo "$out"
 }
 
 runJob() {
-	if ((SCRIPT_OPTS[jobs] > $(jobs | wc -l))); then
+	if ((SCRIPT_OPTS['jobs'] > $(jobs | wc -l))); then
 		"$@" &
 	else
 		"$@"
@@ -306,7 +322,7 @@ edit() {
 					fi
 					out=${out%.*}.opus
 				fi
-				out=$(getFreePath "$out" dst)
+				out=$(ACTION+=.dst getFreePath "$out")
 			fi
 			runCmdWithCleanup "$src" "$out"
 		}
@@ -415,7 +431,7 @@ playParams=(
 declare -A playBuilder=([src]=pickSong)
 pickSong() {
 	declare -n _choice=$1
-	if ((SCRIPT_OPTS[guiPicker] > 0)); then
+	if ((SCRIPT_OPTS['guiPicker'] > 0)); then
 		local cmd=(rofi -dmenu -i -p "$4" -theme-str 'window {width: 50%;}')
 	else
 		local cmd=(fzf --prompt "$4: ")
@@ -589,11 +605,17 @@ resize() {
 
 actionInfo rename R 'rename video/image files'
 renameParams=(
-	videoFormat 'v?' '.+' 'Set `sed` expression for video (default=move year to the front)'
-	audioFormat 'a?' '.+' 'Set `sed` expression for audio (default=strip track number)'
-	imageFormat 'i?' '.+' 'Set timestamp format for images, without extension (default=%Y_%m_%d_%H%M%S)'
+	videoFormat 'v!' '.+' 'Set `sed` expression for video (default=move year to the front)'
+	audioFormat 'a!' '.+' 'Set `sed` expression for audio (default=strip track number)'
+	imageFormat 'i!' '.+' 'Set timestamp format for images, without extension (default=%Y_%m_%d_%H%M%S)'
 	dateFallback 'F?' '[yan]|yes|no|ask' 'Use file mod time for image timestamp fallback (default=a/ask)'
 	src '$+' '$e\.(jpg|JPG|RAF|png|mp4|mkv|flac|opus|mp3)' 'File to rename'
+)
+renameConfig=(
+	videoFormat='s/\./ /g;s/^\(.*\) \([0-9]\{4\}\) .* \(...\)$/\2 \1.\3/'
+	audioFormat='s/^[0-9][0-9] - //'
+	imageFormat='%Y_%m_%d_%H%M%S'
+	dateFallback=ask
 )
 rename() {
 	if [[ -d $src ]]; then
@@ -605,41 +627,45 @@ rename() {
 			src=$src rename
 		done
 	else
-		if [[ $src == *.mp4 || $src == *.mkv ]]; then
-			[[ $videoFormat ]] ||
-				local videoFormat='s/\./ /g;s/^\(.*\) \([0-9]\{4\}\) .* \(...\)$/\2 \1.\3/'
-			local dst=$(echo "$src" | sed "$videoFormat")
-		elif [[ $src == *.flac || $src == *.opus || $src == *.mp3 ]]; then
-			local dst=$(echo "$src" | sed "${audioFormat:-s/^[0-9][0-9] - //}")
-		else
-			local dst="$(exiftool "$src" -d "${imageFormat:-%Y_%m_%d_%H%M%S}" \
-				-p '$DateTimeOriginal' 2>/dev/null).${src##*.}"
+		function isolated() {
+			if [[ $src == *.mp4 || $src == *.mkv ]]; then
+				local dst=$(echo "$src" | sed "$videoFormat")
+			elif [[ $src == *.flac || $src == *.opus || $src == *.mp3 ]]; then
+				local dst=$(echo "$src" | sed "$audioFormat")
+			else
+				local dst="$(exiftool "$src" -d "$imageFormat" \
+					-p '$DateTimeOriginal' 2>/dev/null).${src##*.}"
 
-			if [[ $dst == .* ]]; then # no name, just extension
-				dst="$(date -r "$src" +"${imageFormat:-%Y_%m_%d_%H%M%S}")$dst"
-				[[ $dst == "$src" ]] && return
+				if [[ $dst == .* ]]; then # no name, just extension
+					dst="$(date -r "$src" +"$imageFormat")$dst"
+					[[ $dst == "$src" ]] && return
 
-				if [[ ${dateFallback:-a} == a* ]]; then
-					local dateFallback
-					read -p "$(print "rename '$src' to file mod date ('$dst')? [y/N]: ")" -n1 dateFallback
-					[[ $dateFallback ]] && echo # fix missing newline after input
-				else
-					log Warn "['$src'] - Missing DateTime"
+					if [[ $dateFallback == a* ]]; then
+						local dateFallback
+						read -p "$(print "rename '$src' to file mod date ('$dst')? [y/N]: ")" -n1 dateFallback
+						[[ $dateFallback ]] && echo # fix missing newline after input
+					else
+						log Warn " - Missing DateTime exif data"
+					fi
+
+					if [[ $dateFallback != [yY]* ]]; then
+						log Info " - skipping"
+						return
+					else
+						log Info " - using file modification date"
+					fi
 				fi
 
-				if [[ $dateFallback != [yY]* ]]; then
-					log Info "['$src'] - skipping"
-					return
-				else
-					log Info "['$src'] - using file modification date"
+				[[ $src == "${src%/*}" ]] || dst="${src%/*}/$dst"
+			fi
+			if [[ $src != "$dst" ]]; then
+				dst=$(ACTION+=.dst getFreePath "$dst")
+				if [[ $src != "$dst" ]]; then
+					exec mv "$src" "$dst"
 				fi
 			fi
-
-			[[ $src == "${src%/*}" ]] || dst="${src%/*}/$dst"
-		fi
-		if [[ $src != "$dst" ]]; then
-			exec mv "$src" "$(getFreePath "$dst" dst)"
-		fi
+		}
+		ACTION+="['${src/*\//…/}']" isolated
 	fi
 }
 
diff --git a/bin/sss b/bin/sss
--- a/bin/sss
+++ b/bin/sss
@@ -87,7 +87,7 @@ declare -Ai SCRIPT_OPTS=( # helper + runtime options - changeable by `define` ac
 	[guiPicker]=0
 	[optArgPicker]=0
 	[ignoreFailedPicker]=0
-	[logLvl]=${LOG_LEVELS[info]}
+	[logLvl]=${LOG_LEVELS['info']}
 )
 [[ -t 0 && -t 1 && -t 2 ]] && SCRIPT_OPTS[picker]=1 SCRIPT_OPTS[color]=1
 [[ -t 0 ]] || SCRIPT_OPTS[guiPicker]=1
@@ -106,10 +106,10 @@ defineParams=(
 	ignoreFailedPicker 'I?' '' 'Discard option when picker returned no value'
 	logLvl 'l?' '([0-9]+|[A-Za-km-z]+)?'
 	"Depth of logging, -lll=-l3…\
- (default=${LOG_NAMES[${SCRIPT_OPTS[logLvl]}]}=${SCRIPT_OPTS[logLvl]})"
+ (default=${LOG_NAMES[${SCRIPT_OPTS['logLvl']}]}=${SCRIPT_OPTS['logLvl']})"
 )
 defineParams+=(logLvl '$?' "${defineParams[@]:0-2}")
-SCRIPT_OPTS[logLvl]=${DEBUG:-${SCRIPT_OPTS[logLvl]}}
+SCRIPT_OPTS[logLvl]=${DEBUG:-${SCRIPT_OPTS['logLvl']}}
 define() {
 	declare -i i=0
 	local opt
@@ -146,8 +146,8 @@ define() {
 		elif [[ ${!opt} ]]; then
 			if [[ ${!opt} == [A-Za-z]* && ! ${LOG_LEVELS["${!opt,,}"]} ]]; then
 				[[ $opt == logLvl ]] &&
-					SCRIPT_OPTS["$opt"]=${LOG_LEVELS[info]} ||
-					SCRIPT_OPTS["$opt"]=${LOG_LEVELS[warn]}
+					SCRIPT_OPTS["$opt"]=${LOG_LEVELS['info']} ||
+					SCRIPT_OPTS["$opt"]=${LOG_LEVELS['warn']}
 				log Warn ".$opt - unknown log level '${!opt}', defaulting to '${LOG_NAMES[${SCRIPT_OPTS["$opt"]}]}'
   Available are: ${LOG_NAMES[*]}"
 			else
@@ -165,9 +165,9 @@ define() {
 }
 
 declare -A SSS_OPTS=( # internal behaviour / parsing options - script-specific edge case handling
-	[about]=''                             # script description
-	[exitFn]=exit                          # on error / on successful exit - shouldn't return
-	[exitLogLvl]=$((1 + SCRIPT_OPTS[cli])) # at which level to abort (cli:Error, tui:Fatal)
+	[about]=''                               # script description
+	[exitFn]=exit                            # on error / on successful exit - shouldn't return
+	[exitLogLvl]=$((1 + SCRIPT_OPTS['cli'])) # at which level to abort (cli:Error, tui:Fatal)
 	# set to main registered action if script is a single command - actions act as builders
 	# you can also change other actions' params at runtime → dynamic configuration
 	# builder example: --builder init1 --builderOption --builder init2 'default action arg'
@@ -201,7 +201,7 @@ ansi() {
 	echo "$ret"
 }
 print() {
-	if ((SCRIPT_OPTS[color] <= 0)); then
+	if ((SCRIPT_OPTS['color'] <= 0)); then
 		echo "$@"
 		return
 	fi
@@ -269,20 +269,20 @@ print() {
 #######################################
 log() {
 	LAST_LOG_LVL=${LOG_LEVELS["${1,,}"]:-$1}
-	if ((SCRIPT_OPTS[logLvl] >= LAST_LOG_LVL)); then
+	if ((SCRIPT_OPTS['logLvl'] >= LAST_LOG_LVL)); then
 		local type=${LOG_NAMES[$LAST_LOG_LVL]}
-		((SCRIPT_OPTS[color] > 0)) && type=$(ansi "$type" "${type^^}" fg) || type=${type^^}
+		((SCRIPT_OPTS['color'] > 0)) && type=$(ansi "$type" "${type^^}" fg) || type=${type^^}
 		echo "$type$(print ": $ACTION$2")" 1>&2
 	fi
-	if ((SSS_OPTS[exitLogLvl] >= LAST_LOG_LVL)); then
-		[[ $ACTION == ${SSS_OPTS[exitFn]} ]] && exit -1 || "${SSS_OPTS[exitFn]}" $LAST_LOG_LVL
+	if ((SSS_OPTS['exitLogLvl'] >= LAST_LOG_LVL)); then
+		[[ $ACTION == ${SSS_OPTS['exitFn']} ]] && exit -1 || "${SSS_OPTS['exitFn']}" $LAST_LOG_LVL
 	fi
 }
 
 # Supports simple redirection ... '>'/'>>' 'path'
 exec() {
-	((SCRIPT_OPTS[logLvl] > 3)) && log Verbose " \$> $*"
-	((SCRIPT_OPTS[dryRun] > 0)) && return
+	((SCRIPT_OPTS['logLvl'] > 3)) && log Verbose " \$> $*"
+	((SCRIPT_OPTS['dryRun'] > 0)) && return
 	if [[ ${*:0-2:1} == \>* ]]; then
 		if [[ ${*:0-2:1} == \>\> ]]; then
 			"${@:1:$#-2}" >>"${!#}"
@@ -295,19 +295,19 @@ exec() {
 }
 
 main() {
-	if ((SCRIPT_OPTS[cli] > 0)); then
+	if ((SCRIPT_OPTS['cli'] > 0)); then
 		while (($#)); do
 			parseAction "$@"
 			shift $?
 		done
-		((SCRIPT_OPTS[tui] > 0)) || quit
+		((SCRIPT_OPTS['tui'] > 0)) || quit
 		SCRIPT_OPTS[cli]=0
 	fi
 
 	SCRIPT_OPTS[picker]=1
 	local _esc
 	while :; do
-		if ((SCRIPT_OPTS[optArgPicker])); then
+		if ((SCRIPT_OPTS['optArgPicker'])); then
 			read -rp "Choose $(ansi italic action noitalic delim \( oper + param opts delim \): fg) " line
 		else
 			read -rp "Choose $(ansi italic action noitalic delim : fg) " -n 1 line
@@ -330,7 +330,7 @@ main() {
 			parseAction -$line
 		else
 			local _prefix=
-			while [[ ! $_prefix =~ ^${SSS_OPTS[optPrefix]}$ ]]; do
+			while [[ ! $_prefix =~ ^${SSS_OPTS['optPrefix']}$ ]]; do
 				_prefix+=-
 			done
 			parseAction $_prefix$line
@@ -345,7 +345,7 @@ parseAction() {
 
 	local ACTION actionArg
 	log Trace "parsing $1"
-	if [[ $1 =~ ^(${SSS_OPTS[optPrefix]})([^-][^=]+)(=.*)?$ ]] && { # full action name
+	if [[ $1 =~ ^(${SSS_OPTS['optPrefix']})([^-][^=]+)(=.*)?$ ]] && { # full action name
 		actionArg=${BASH_REMATCH[3]:1}
 		ACTION=$(
 			isAction() { [[ ${ACTION_INFO["$1"]} ]]; }
@@ -363,7 +363,7 @@ parseAction() {
 			shift
 		fi
 	else
-		ACTION=${SSS_OPTS[defAction]}
+		ACTION=${SSS_OPTS['defAction']}
 	fi
 	unset actionArg
 
@@ -378,7 +378,7 @@ parseAction() {
 	while (((i += 4) < sigN)); do
 		local sign=${sigs[i + 1]}
 		((${#sign} == 2)) || log Fatal "Params[$((i + 1))] should contain signature, but has '$sign'!"
-		[[ $sign != \$? || ${SSS_OPTS[argAsLongOpt]} -gt 0 ]] && opts["${sigs[$i]}"]="$i"
+		[[ $sign != \$? || ${SSS_OPTS['argAsLongOpt']} -gt 0 ]] && opts["${sigs[$i]}"]="$i"
 		[[ $sign != [_$]? ]] && opts["${sign::1}"]=$i # '_'=no short, '$'=arg
 		[[ $sign == ?[+!] || $sign == \$? ]] && posArg=${posArg:-$i} args[$i]=0
 	done
@@ -415,7 +415,8 @@ parseAction() {
 			fi
 
 			local i='' optCnt=+ tmpArr=
-			if [[ $# -ne $actionArgFromEnd && $1 =~ ^(${SSS_OPTS[optPrefix]})(no-)?([^- ][^= ]+)(=.*)?$ ]] && {
+			if [[ $# -ne $actionArgFromEnd &&
+				$1 =~ ^(${SSS_OPTS['optPrefix']})(no-)?([^- ][^= ]+)(=.*)?$ ]] && {
 				tmpArr=("${BASH_REMATCH[@]}")
 				i=$( # index for full option name
 					isOpt() { [[ ${opts["$1"]} ]]; }
@@ -456,16 +457,16 @@ parseAction() {
 					else
 						shift
 					fi
-				elif [[ (! ${arg+y} || $optChain) && ${SSS_OPTS[onNoArg]} -ge 0 ]] && argMatch; then
+				elif [[ (! ${arg+y} || $optChain) && ${SSS_OPTS['onNoArg']} -ge 0 ]] && argMatch; then
 					declare -i "$varName+=${optCnt}1"
 					log Debug ".$varName = ${!varName}"
-				elif [[ (! ${arg+y} || $optChain) && ${SSS_OPTS[onNoArg]} -gt 0 &&
-					${SCRIPT_OPTS[picker]} -gt 0 ]] && {
+				elif [[ (! ${arg+y} || $optChain) && ${SSS_OPTS['onNoArg']} -gt 0 &&
+					${SCRIPT_OPTS['picker']} -gt 0 ]] && {
 
 					[[ ${sigs[i + 1]} == ?[+*] ]] && declare -a "$varName" || local "$varName"
 
 					"${builder["$varName"]:=$(determinePicker "$reg")}" "${sigs[@]:i:4}" || {
-						((${SCRIPT_OPTS[ignoreFailedPicker]} > 0)) && i=-1
+						((${SCRIPT_OPTS['ignoreFailedPicker']} > 0)) && i=-1
 					}
 				}; then
 					if ((i < 0)); then
@@ -540,8 +541,8 @@ parseAction() {
 		[[ ${args[$i]} != 0 ]] && continue # opts don't have an entry, filled args > 0
 
 		# picker for optional args || arg required
-		if [[ ${SCRIPT_OPTS[picker]} -gt 0 &&
-			(${SCRIPT_OPTS[optArgPicker]} -gt 0 || $sign == ?[+!]) ]]; then
+		if [[ ${SCRIPT_OPTS['picker']} -gt 0 &&
+			(${SCRIPT_OPTS['optArgPicker']} -gt 0 || $sign == ?[+!]) ]]; then
 			declare -a "$varName"
 			if "${builder["$varName"]:=$(determinePicker "$reg")}" "${sigs[@]:i:4}"; then
 				args[$i]+=1
@@ -559,7 +560,7 @@ parseAction() {
 	unset sigs i sigN args builder varName sign reg
 
 	# ensure valid state
-	if [[ $ACTION == "${SSS_OPTS[defAction]}" && $# -gt 0 && ${SSS_OPTS[defActionLast]} ]]; then
+	if [[ $ACTION == "${SSS_OPTS['defAction']}" && $# -gt 0 && ${SSS_OPTS['defActionLast']} ]]; then
 		log Error " - Default action must use all args, but some were left: $*"
 	fi
 
@@ -576,7 +577,7 @@ declare -A REGEX=(
 	[var]='[A-Za-z_][0-9A-Za-z_]*' [dashvar]='[A-Za-z_][0-9A-Za-z_-]*'
 	[const]='[A-Z_][0-9A-Z_]*' [domain]='[a-z0-9]+\.[0-9a-z.]+'
 )
-REGEX[email]="${REGEX[var]}@${REGEX[domain]}"
+REGEX[email]="${REGEX['var']}@${REGEX['domain']}"
 REGEX[str]="\"[^\"]*\"|'([^']|'[A-Za-z])*'|\`[^\`]*\`"
 
 #######################################
