fix(mom): renaming now works again

diff --git a/bin/mom b/bin/mom
--- a/bin/mom
+++ b/bin/mom
@@ -241,6 +241,7 @@ runJob() {
 }
 
 # expects $cmd, $keepSrc, $src, $dst, $out
+# moves $out to $src if ! $dst 
 runCmdWithCleanup() {
 	exec "${cmd[@]}" "$out" && if ((keepSrc <= 0)); then
 		[[ ${src#./} == "${out#./}" ]] || exec rm "$src"
@@ -361,6 +362,7 @@ edit() {
 				out=$dst # file $dst has priority
 			else
 				if [[ $rename ]]; then
+					[[ $dst ]] || dst=. # to prevent runCmdWithCleanup renaming the output back
 					out=$(call rename "${renameConfig[@]}" "$src" '-')
 					out=${out%.*}
 					out=${out%_1}
@@ -709,7 +711,7 @@ renameConfig=(
 	format=mov:'$DateTimeOriginal'
 	format=image:'$DateTimeOriginal'
 	fallback=video:'s,\., ,g;s,^(.*/)?(.*) ([0-9]{4}) .*$,\1\3 \2,'
-	fallback=audio:'s,.*(/([^0-9]+( \w+)+)/).*- ?,\2 - ,'
+	fallback=audio:'s,.*(/([^0-9 ]+( \w+)+)[^/]*/).*[0-9.-]+ ?,\2 - ,'
 	dateFormat='%Y-%m-%d_%H%M%S'
 	useDateFallback=ask
 )
