fix: new sway update

diff --git a/bin/mom b/bin/mom
--- a/bin/mom
+++ b/bin/mom
@@ -31,7 +31,7 @@ download() { # TODO: allow video; allow qual/fmt selection through a picker
 	local cmd=(yt-dlp -q -N 8 -f "${format:-ba[ext=${ext/opus/webm}]/ba}")
 	[[ $dst ]] || local dst=.
 	[[ -d $dst ]] && local tmp="%(creator)s - %(title)s" || local tmp=${dst##*/}
-	local prefix=/tmp/mom-download
+	local prefix=/tmp/mom-$ACTION
 	declare -i i=-1 srcN=${#src[@]}
 
 	while ((++i < srcN)); do
@@ -47,7 +47,7 @@ download() { # TODO: allow video; allow qual/fmt selection through a picker
 				ffprobe "$cmd" |& grep 'Audio: aac' -q && local ext=m4a || local ext=opus
 				exec mv -f "$cmd" "$file"
 
-				((metadata >= 0)) && cmd=(mv) || cmd=(call edit +c +k)
+				((metadata >= 0)) && cmd=(mv) || cmd=(call edit +c --delete-src)
 				cmd+=("$file")
 				[[ -d $dst ]] && cmd+=("${dst%/}/$(
 					sed -e 's/\(.* -\) \1/\1/' -e 's/^NA - //' -e 's/ [([].*[])]//g' \
@@ -519,7 +519,7 @@ subtitles() {
 		local dst=${vid%.*}.mkv
 		[[ -f $dst ]] && dst="${vid%.*} $lang-sub.mkv"
 	fi
-	local tmp="/tmp/mom-${dst##*/}"
+	local tmp=$(ACTION+=.tmpFile getFreePath "/tmp/mom-${dst##*/}")
 	cmd+=("$tmp")
 
 	exec "${cmd[@]}" && exec mv "$tmp" "$dst" && if ((deleteSrc > 0)); then
@@ -637,7 +637,7 @@ play() {
 			exec "${cmd[@]}" && exec "$0" $ACTION -L --randomizer=$randomizer "${src[@]}" &
 		else # for whatever reason cmds launched via terminal, but from desktop ignore disown
 			log Verbose && log Verbose " \$> ${cmd[*]} &"
-			nohup "${cmd[@]}" >/dev/null 2>&1 &
+			nohup "${cmd[@]}" &>/dev/null &
 			disown
 		fi
 		sleep 1
@@ -682,6 +682,7 @@ linkFix() {
 actionInfo resize 'resize images'
 resizeParams=(
 	deleteSrc 'd?' '' 'Delete $src file'
+	rename 'r?' '' 'If output should be renamed according to its exif data'
 	src '$+' "${MIME_TYPES['image']}" 'File to resize'
 	quality 'q?' '[0-9]+' 'Change image quality (default=original quality)'
 	predicate 'p*' '[0-9]+%?[+-]' 'Source size requirement, pixels or % of the target size
@@ -719,22 +720,18 @@ resize() {
 				local pred
 				for pred in "${predicate[@]}"; do
 					((dim[0] < dim[1])) && dim=(${dim[1]} ${dim[0]})
-					local gap=${pred::-1} only=${pred:0-1}
+					local gap=${pred::-1} only=${pred:0-1} # number + sign
 					if [[ $gap == *% ]]; then
 						((gap = ${gap%'%'} * ${size%'^'} / 100))
 						log Verbose ".predicate: $pred → $gap$only"
 					fi
 
 					# select compared dimension - `^` for shortest side
-					if [[ $size == *^ ]]; then
-						dim=${dim[1]}
-					elif [[ $size != *x* ]]; then
-						size=${size}x$size # to fix portraits being resized by width instead of height
-					fi
+					[[ $size == *^ ]] && dim=${dim[1]}
 
 					# require distance to target size greater/lower or equal to $gap
 					if ! [[ ($only == + && $dim -ge $gap) || ($only == - && $dim -le $gap) ]]; then
-						if [[ $dst ]]; then # no conversion, only move to destination
+						if [[ ${src#./} != ${out#./} ]]; then # no conversion, only move to destination
 							exec $( ((deleteSrc <= 0)) && echo cp || echo mv) "$src" "${out%.*}.${src##*.}"
 						fi
 						log Info ": ${dim}px != <${gap}px${only}> → skipping"
@@ -743,10 +740,16 @@ resize() {
 				done
 			fi
 
+			if [[ $size != *^ && $size != *x* ]]; then
+				size="${size}x$size" # enforcement of long side (magick mangles it with short otherwise)
+			fi
+
 			local cmd=(magick "$src" -auto-orient -resize "$size")
 			((quality)) && cmd+=(-quality $quality)
 
-			runCmdWithCleanup
+			runCmdWithCleanup && if ((rename)); then # code structure to keep the exit code of the cmd
+				NO_CONFIG=0 call rename "$out"
+			fi
 		}
 		ACTION+="['${src/*\//…/}']" runJob isolated
 	done
@@ -764,10 +767,10 @@ arrayToMap() {
 
 actionInfo rename R 'rename video/image files using `exiftool` with `sed` fallback'
 renameParams=(
-	format 'f*' '[^:]+[:=].*' 'Exiftool format per argMatch expression'
-	fallback 'F*' '[^:]+[:=].*' 'Sed fallback expression per argMatch expression'
+	format 'f*' '[^:]+[:=].*' 'Exiftool format per argMatch expression (last match used)'
+	fallback 'F*' '[^:]+[:=].*' 'Sed fallback expression per argMatch expression (last match used)'
 	dateFormat 'd!' '.+' 'Timestamp format'
-	dateFallback 'D?' '[yan]|yes|no|ask' 'Use file mod time for timestamp fallback'
+	dateFallback 'D?' '' 'Use file mod time for timestamp fallback (default=ask)'
 	extension 'e?' '.?[0-9a-z]+' 'Look for a free name with this extension'
 	src '$+' "\$d${MIME_TYPES['video']}${MIME_TYPES['audio']}${MIME_TYPES['image']}" 'File to rename'
 	dst '$?' '$d$|-' 'Destination to rename to, or `-` to just print the final dst'
@@ -779,12 +782,16 @@ renameConfig=(
 	format=${MIME_TYPES['image']}:'$DateTimeOriginal'
 	fallback=${MIME_TYPES['video']}:'s,\., ,g;s,^(.*/)?(.*) ([0-9]{4}) .*$,\1\3 \2,' # movies
 	fallback=${MIME_TYPES['audio']}:'s,.*/([A-Z][a-z]+( \w+)+).*/([0-9.]+|.*-) ([^_/]+)(_[0-9]*)?$,\1 - \4,'
-	fallback=${MIME_TYPES['image']}:'s,IMG-(....)(..)(..)-WA(....)$,\1-\2-\3_00\4,'
+	fallback=${MIME_TYPES['image']}:'s,IMG-(....)(..)(..)-(WA....)$,\1-\2-\3_\4,'
 	dateFormat='%Y-%m-%d_%H%M%S'
-	dateFallback=ask
 )
 rename() {
 	if ((${#src[@]} > 1)); then
+		if [[ -d ${src[-1]} && -z $dst ]]; then # dst dir parsed as src
+			local dst=${src[-1]}
+			src=("${src[@]::${#src[@]}-1}")
+		fi
+
 		for src in "${src[@]}"; do
 			src=$src rename # to pass a string instead of an array
 		done
@@ -795,18 +802,24 @@ rename() {
 	else
 		function isolated() {
 			local name=${src##*/}
-			for pair in "${format[@]}"; do
-				if matcher=${pair/:*/} argMatch "$name"; then
-					local exif=${pair#*:}
+			declare -i i=${#format[@]}
+
+			while ((i-- > 0)); do
+				if matcher=${format[$i]/:*/} argMatch "$src"; then
+					local exif=${format[$i]#*:}
 					break
 				fi
 			done
-			for pair in "${fallback[@]}"; do
-				if matcher=${pair/:*/} argMatch "$name"; then
-					local sed=${pair#*:}
+			log Debug ".exif = '$exif'"
+
+			i=${#fallback[@]}
+			while ((i-- > 0)); do
+				if matcher=${fallback[$i]/:*/} argMatch "$src"; then
+					local sed=${fallback[$i]#*:}
 					break
 				fi
 			done
+			log Debug ".sed = '$sed'"
 
 			local ext=${name##*.}
 			ext=${ext,,}
@@ -823,22 +836,20 @@ rename() {
 						)" 2>/dev/null
 					) && [[ $name ]]
 				} || { # date fallback (for images); relies on datetime being the only exif var
-					[[ $exif =~ ^[^$]*\$DateTimeOriginal[^$]*$ ]] && {
+					[[ $dateFallback -ge 0 && $exif =~ ^[^$]*\$DateTimeOriginal[^$]*$ ]] && {
 						name="${exif/'$DateTimeOriginal'*/}$(
 							date -r "$src" +"$dateFormat"
 						)${exif/*'$DateTimeOriginal'/}"
-						[[ $name == "${src%.*}" ]] && dateFallback=y
-						echo "test $name $dateFallback"
+						[[ $name == "${src%.*}" ]] && dateFallback=1
 
-						if [[ $dateFallback == a* ]]; then
+						if ((!dateFallback)); then
 							local dateFallback
 							read -p "$(
 								print "rename '$src' to file mod date = '$name.$extension'? [y/N]: "
 							)" -n1 dateFallback
 							[[ $dateFallback ]] && echo # fix missing newline after user input
+							[[ $dateFallback == [yY]* ]] && dateFallback=$?
 						fi
-
-						[[ $dateFallback == [yY]* ]]
 					}
 				}
 			} || { # sed fallback
@@ -846,7 +857,7 @@ rename() {
 					[[ $src == *[^.]/* ]] || src=$PWD/${src#./}
 					name=$(echo "${src%.*}" | sed -E "$sed")
 					[[ $exif ]] &&
-						log Warn " - Missing '$exif' exif data, fallback name: '${name##*/}.$extension'"
+						log Warn " - using fallback: '${name##*/}.$extension'"
 					[[ $name ]]
 				}
 			}; then
@@ -872,60 +883,27 @@ rename() {
 	fi
 }
 
-actionInfo exifFilter f 'exif-[f]ilter' 'filter files by exif data using fzf'
-exifFilterParams=(
-	sourcesCmd 'S+' '.*' 'Command+args for finding files from sources'
-	sourcesOpts 's?' '.+' 'Splitted flags for sources command'
-	dateFormat 'D!' '.+' 'Timestamp format'
-	delimiter 'd!' '.+' 'Separator between filename and exif data'
-	exifOpts 'e?' '.+' 'Splitted exiftool options'
-	exifAwkFilter 'R?' '.+' 'Awk expression for what to use when $exif is not set'
-	exif '$?' '$E.+' 'Exiftool format to use for filtering (filters all exif by default)'
-	src '$*' '$e$|-' 'Files/directories to filter recursively (default=.)'
-	filterCmd 'F*' '.*' 'Filtering command with options'
-	filterOpts 'f?' '.+' 'Splitted flags for filter command'
-)
-exifFilterConfig=(
-	sourcesCmd='fd' -S '' -S '-Lt' -S 'f'
-	dateFormat='%Y-%m-%d_%H:%M:%S'
-	delimiter='$: '
-	exifAwkFilter='! /^(File|Exif|Profile|SubSec|Offset|Dir|Doc|Disp)/'
-	filterCmd='fzf'
-)
-exifFilter() {
-	local f o
-	if [[ $src == - ]]; then
-		local src=()
-		while read f; do
-			src+=("$f")
-		done
+actionInfo concat 'concatenate files using ffmpeg concat demuxer'
+concatParams=(
+	deleteSrc 'd?' '' 'Delete $src files'
+	metadataSource 'm?' "\$f$|${REGEX[int]}" 'Which source to use for metadata copying (idx or path)'
+	rename 'r?' '' 'If output should be renamed according to its exif data'
+	src '$+' "${MIME_TYPES['video']}${MIME_TYPES['audio']}" 'Files to concatenate'
+	dst '$?' '$d$F' 'Output file (default=`$src[metadataSource]`)')
+concat() {
+	tmpFile=$(ACTION+=.tmpFile getFreePath /tmp/mom-$ACTION.txt)
+	printf "file '%s'\n" "${src[@]}" >"$tmpFile"
+
+	[[ ! -f ${metadataSource:-0} ]] && local metadataSource=${src[${metadataSource:-0}]}
+	local out ext dst=${dst}
+	src=${metadataSource%.*}.${src##*.} determineOut
+	cat "$tmpFile"
+
+	local cmd=($(ffmpegCmd) -f concat -i "$tmpFile" -c copy)
+	runCmdWithCleanup && exec exiftool -TagsFromFile "$metadataSource" -'Media*Date' \
+		-'Track*date' -CreateDate -ModifyDate -overwrite_original "$out" && if ((rename)); then
+		dst= NO_CONFIG=0 call rename "$out"
 	fi
-
-	local files=()
-	while read f; do
-		files+=("$f")
-	done < <("${sourcesCmd[@]}" ${sourcesOpts[*]} "${src[@]-.}")
-
-	[[ $files ]] || log Error ".sourcesCmd - 0 files found"
-
-	exiftool ${exifOpts--fast2 -s2 ${exif:+-p "\$Directory/\$FileName${delimiter//'$'/'$$'}$exif"}} \
-		-d "$dateFormat" "${files[@]}" 2>/dev/null | {
-		if [[ ! $exifOpts && ! $exif ]]; then
-			((${#files[@]} == 1)) && printf '%s' "$files$delimiter"
-			awk '/^=/ {if (line) print line; sub("^=* ", ""); line=$0"'"$delimiter"'"};
-				'"$exifAwkFilter"' && $1 ~ /:$/ {line=line$0";"};
-				END {if (line) print line}'
-		else
-			cat
-		fi
-	} | {
-		if [[ $filterCmd || $filterOpts ]]; then
-			"${filterCmd[@]}" ${filterOpts[*]} |
-				sed "s/$(echo "$delimiter" | sed 's/.*\([$^*.\\[\]\/]\)/\\\1/g').*//"
-		else
-			cat
-		fi
-	}
 }
 
 SSS_OPTS[exitFn]=exitFnMom
@@ -934,4 +912,4 @@ exitFnMom() {
 	exitFn "$@"
 }
 
-main "$@" # TODO: default action that determines the right action to give the argument(s) to
+main "$@"
