fix(mom): automatic volume levelling

diff --git a/bin/mom b/bin/mom
--- a/bin/mom
+++ b/bin/mom
@@ -5,11 +5,9 @@
 SSS_OPTS[about]='MOM - Media Operation&Manipulation
 A collection of media operation/manipulation scripts.'
 
-((SCRIPT_OPTS[jobs] = (1 + $(nproc --all)) / 2))
 SCRIPT_OPTS[freePathNumberReuse]=0
 SCRIPT_OPTS[ffmpegLogLvl]=2
 defineParams=(
-	jobs 'j?' '[0-9]*' "Number of jobs to run in parallel (default=${SCRIPT_OPTS['jobs']})"
 	freePathNumberReuse 'N?' '' 'Increment numbers in paths without appending (default=0)'
 	ffmpegLogLvl 'f?' '-?[0-9]*' 'Set ffmpeg log level or +f to use the script $logLvl'
 	"${defineParams[@]}")
@@ -100,7 +98,17 @@ mpvPicker() {
 				f:close()
 			end
 			local function addVolume()
+lua
+		if [[ $volume != -* ]]; then # don't change volume if an absolute value in dB was set
+			cat >>"$pickerFile" <<lua
 				add('volume', mp.get_property_number 'volume' / 100)
+lua
+		else
+			cat >>"$pickerFile" <<lua
+				add('volume', '$volume')
+lua
+		fi
+		cat >>"$pickerFile" <<lua
 			end
 			
 			-- NOTE: maybe do dynamically from action regex defs?
@@ -160,7 +168,7 @@ $(print "<Enter> to pick --volume and quit")"}" --script="$pickerFile"
 	declare +n arr
 }
 mpvVolumePicker() {
-	DEFAULT_VALUE=1 mpvPicker "$@"
+	DEFAULT_VALUE=${volume:-1} mpvPicker "$@"
 }
 timeToSeconds() {
 	local str=${1#0}
@@ -232,16 +240,8 @@ genDstFromSrc() {
 	echo "$out"
 }
 
-runJob() {
-	if ((SCRIPT_OPTS['jobs'] > $(jobs | wc -l))); then
-		IS_JOB=1 "$@" &
-	else
-		"$@"
-	fi
-}
-
 # expects $cmd, $keepSrc, $src, $dst, $out
-# moves $out to $src if ! $dst 
+# moves $out to $src if ! $dst
 runCmdWithCleanup() {
 	exec "${cmd[@]}" "$out" && if ((keepSrc <= 0)); then
 		[[ ${src#./} == "${out#./}" ]] || exec rm "$src"
@@ -268,7 +268,7 @@ editParams=(
 	fadeoutEnd 'F*' "${REGEX['timestamp']}"
 	'End of fadeout, or fadeout duration, priority: -e > -F > -p'
 	end 'e*' "${REGEX['timestamp']}" 'End time, or seconds from the end (default=0)'
-	volume 'v*' '[0-9]+(\.[0-9]+)?' 'Volume multiplier (default=1)'
+	volume 'v*' '-?[0-9]+(\.[0-9]+)?(dB|LUFS)?' 'Volume multiplier or target dB (default=1)'
 	pickAll 'a?' '' 'Use a picker for all timestamp values + volume'
 	dst '$?' '$d$D\.(opus|mp3|m4a|flac|wma)' 'Output file/dir (default=`$src.opus`, deletes `$src`)')
 edit() {
@@ -278,7 +278,7 @@ edit() {
 	fi
 
 	if ((pickAll > 0)); then
-		declare -a volume
+		[[ $volume ]] || declare -a volume
 		mpvVolumePicker volume || return 1
 
 		local opt
@@ -302,9 +302,9 @@ edit() {
 
 			if ((copy <= 0)); then
 				local b=${bitrate[i]:-$bitrate}
-				local srcBr=$(ffprobe "$src" |& sed -n 's#.*Audio: .*, \([0-9]\+\) kb/s.*#\1#p')
+				local srcBr=$(ffprobe "$src" |& sed -n 's#.*bitrate: \([0-9]\+\) kb/s.*#\1#p')
 				if [[ -z $b ]]; then
-					[[ ($src == *.opus && $srcBr -ge 128) ||
+					[[ ($src == *.opus && $srcBr -ge 118) ||
 						$src =~ \.(flac|wav)$ || $srcBr -ge 256 ]] && b=128 || b=96
 					log Info ".bitrate = $b"
 				fi
@@ -353,6 +353,29 @@ edit() {
 			fi
 
 			local v=${volume[i]:-${volume:-1}}
+			if [[ $v == -* ]]; then
+				if [[ $v == *dB ]]; then
+					v=$(
+						ffmpeg -hide_banner -i "$src" -af volumedetect -f null - |&
+							sed -En "s,.*mean_volume: -([0-9.]+) dB,${v%dB}+\1,p" | bc
+					)
+				elif [[ $v == *LUFS ]]; then
+					v=$(
+						ffmpeg -hide_banner -i "$src" -af loudnorm=print_format=summary -f null - |&
+							sed -En "s,Input Integrated:.*-([0-9.]+) LUFS,${v%LUFS}+\1,p" | bc
+					) # currently we only change measurement method, not adaptation method (loudnorm)
+				else
+					log Error ": Invalid --volume=$v - either dB or LUFS"
+				fi
+
+				if [[ ($v == 0* || $v == .*) && ${v#*.} -lt 4 ]]; then
+					log Info ": Volume difference = 0${v#0}dB -> not changing"
+					v=1
+				else
+					v+=dB
+					log Info ".volume = $v"
+				fi
+			fi
 			if [[ $v != 1 ]]; then
 				[[ $fE ]] && cmd[-3]+=,volume=$v || cmd+=(-af volume=$v)
 			fi
@@ -363,7 +386,7 @@ edit() {
 			else
 				if [[ $rename ]]; then
 					[[ $dst ]] || dst=. # to prevent runCmdWithCleanup renaming the output back
-					out=$(call rename "${renameConfig[@]}" "$src" '-')
+					out=$(call rename "${renameConfig[@]}" "$src" '-' 3>/dev/null)
 					out=${out%.*}
 					out=${out%_1}
 					if [[ $out ]]; then
@@ -376,7 +399,7 @@ edit() {
 
 			if [[ -d ${dst:-.} ]]; then
 				if ((copy <= 0)); then # if codec is not being copied already, try to copy if possible
-					if [[ $copy -eq 0 && $src == *.opus && $v == 1 && -z $fE && $srcBr == $b ]]; then
+					if [[ $copy -eq 0 && $src == *.opus && $v == 1 && -z $fE ]]; then
 						log Info '.copy = true (no reencoding required)'
 						cmd=("${cmd[@]::cmdBitratePos-2}" -c copy "${cmd[@]:cmdBitratePos}")
 					fi
@@ -384,6 +407,7 @@ edit() {
 				fi
 				out=$(ACTION+=.dst getFreePath "$out")
 			fi
+			[[ $src == $PWD/* ]] && src=${src#"$PWD"/}
 			runCmdWithCleanup
 		}
 		ACTION+="['${src/*\//…/}']" runJob isolated
@@ -510,6 +534,7 @@ play() {
 	((NO_LOOP > 0)) || cmd+=(--loop-playlist)
 
 	if [[ -f $src ]]; then
+		local file=true
 		exec printf '%s\n' "${src[@]}" \> "$playlistFile"
 		cmd+=(--playlist-start=0)
 		src=${src%/*}
@@ -711,7 +736,7 @@ renameConfig=(
 	format=mov:'$DateTimeOriginal'
 	format=image:'$DateTimeOriginal'
 	fallback=video:'s,\., ,g;s,^(.*/)?(.*) ([0-9]{4}) .*$,\1\3 \2,'
-	fallback=audio:'s,.*(/([^0-9 ]+( \w+)+)[^/]*/).*[0-9.-]+ ?,\2 - ,'
+	fallback=audio:'s,.*/([A-Z][a-z]+( \w+)+).*/([0-9.]+|.*-) ([^_/]+)(_[0-9]*)?$,\1 - \4,'
 	dateFormat='%Y-%m-%d_%H%M%S'
 	useDateFallback=ask
 )
@@ -855,8 +880,6 @@ exifFilter() {
 
 SSS_OPTS[exitFn]=exitFnMom
 exitFnMom() {
-	((IS_JOB)) && exit
-
 	rm -f /tmp/mom-*
 	exitFn "$@"
 }
