feat(sss): file matching with special case values

diff --git a/bin/sss b/bin/sss
--- a/bin/sss
+++ b/bin/sss
@@ -6,10 +6,10 @@ declare -a ACTION_ORDER=()
 ALIGNER=8
 
 argToCase() {
-	[[ $1 != *-* ]] && {
+	if [[ $1 != *-* ]]; then
 		echo "$1"
 		return
-	}
+	fi
 
 	local str=${1#*-}
 	local ret=${1%%-*}
@@ -22,10 +22,10 @@ argToCase() {
 	echo "$ret${str^}"
 }
 caseToArg() {
-	[[ $1 != *[A-Z]* ]] && {
+	if [[ $1 != *[A-Z]* ]]; then # no uppercase letters
 		echo "${1//_/-}"
 		return
-	}
+	fi
 
 	local str=$1
 	local ret=''
@@ -67,9 +67,9 @@ actionInfo() {
 		local converted=$(caseToArg "$name")
 		[[ $key ]] && helpsig="[$key]${converted:1}" || helpsig=$converted
 	fi
-	[[ $key ]] && ACTION_INFO[$key]="$name"
+	[[ $key ]] && ACTION_INFO["$key"]="$name"
 	((ALIGNER < ${#helpsig})) && ALIGNER=${#helpsig}
-	ACTION_INFO[$name]="$helpsig $help"
+	ACTION_INFO["$name"]="$helpsig $help"
 	ACTION_ORDER+=("$name")
 }
 
@@ -86,6 +86,7 @@ declare -Ai SCRIPT_OPTS=( # helper + runtime options - changeable by `define` ac
 	[picker]=0
 	[guiPicker]=0
 	[optArgPicker]=0
+	[ignoreFailedPicker]=0
 	[logLvl]=3
 )
 [[ -t 0 && -t 1 && -t 2 ]] && SCRIPT_OPTS[picker]=1 SCRIPT_OPTS[color]=1
@@ -93,17 +94,22 @@ declare -Ai SCRIPT_OPTS=( # helper + runtime options - changeable by `define` ac
 
 actionInfo define D 'set script-processing options'
 defineParams=(
-	tui 't?' '' 'Enter TUI after CLI is parsed'
-	dryRun 'd?' '' 'Disable actual commands execution'
+	tui 'T?' '' 'Enter TUI after CLI is parsed'
+	dryRun 'D?' '' 'Disable actual commands execution'
 	color 'C?' '' 'Colorize output (default=1 when not redirected)'
-	config 'c*' '$f.conf.sh' 'Config file as arrays of cli options like `defineConfig+=(-l3)`'
-	picker 'p?' '' 'Enable arg/opt param picker (default=1 for TUI, 0 for CLI)'
-	guiPicker 'g?' '' 'Use GUI pickers'
-	optArgPicker 'o?' '' 'Enable picker for optional arguments'
+	config 'c*' '$f\.conf\.sh$|-?'
+	"Config file as arrays of cli options like \`defineConfig+=(-l3)\`,\
+ or \`+c\` to unload all configs (default='~/.config/${0/*\//}.conf.sh')"
+	picker 'p?' '' 'Enable arg/opt param picker (default=1 when stdin is available)'
+	guiPicker 'g?' '' 'Use GUI pickers (default=1 when stdin is missing)'
+	optArgPicker 'o?' '' 'Enable picker for optional arguments (options and `$?`/`$*` args)'
+	ignoreFailedPicker 'I?' '' 'Discard option when picker returned no value'
 	logLvl 'l?' '([0-9]+|[A-Za-km-z]+)?'
-	"Depth of logging, -lll=-l3… (default=${LOG_NAMES[${SCRIPT_OPTS[logLvl]}]}=${SCRIPT_OPTS[logLvl]})"
+	"Depth of logging, -lll=-l3…\
+ (default=${LOG_NAMES[${SCRIPT_OPTS[logLvl]}]}=${SCRIPT_OPTS[logLvl]})"
 )
 defineParams+=(logLvl '$?' "${defineParams[@]:0-2}")
+SCRIPT_OPTS[logLvl]=${DEBUG:-${SCRIPT_OPTS[logLvl]}}
 define() {
 	declare -i i=0
 	local opt
@@ -112,40 +118,56 @@ define() {
 		if [[ ! ${!opt} ]]; then
 			:
 		elif [[ -z ${defineParams[i + 2]} ]]; then
-			SCRIPT_OPTS[$opt]=${!opt}
+			SCRIPT_OPTS["$opt"]=${!opt}
 		elif [[ $opt == config ]]; then
 			declare -n opt
 			local x
 			for x in "${opt[@]}"; do
-				source "$x" || log Error ".config - invalid syntax in '$x'"
+				if [[ $x =~ ^-?[0-9]*$ ]]; then
+					if [[ $x == - || $x -lt 0 ]]; then
+						local _act
+						for _act in "${ACTION_ORDER[@]}"; do
+							unset "${_act}Config"
+						done
+						unset _act
+						continue
+					else
+						x=${XDG_CONFIG_HOME:-$HOME/.config}/${0/*\//}.conf.sh
+					fi
+				fi
+
+				if [[ -f $x ]]; then
+					source "$x" || log Error ".config['$x'] - invalid syntax"
+				elif [[ $ACTION == define ]]; then # called by user
+					log Warn ".config['$x'] doesn't exist"
+				fi
 			done
 			declare +n opt
 		elif [[ ${!opt} ]]; then
-			if [[ ${!opt} == [A-Za-z]* && ! ${LOG_LEVELS[${!opt,,}]} ]]; then
+			if [[ ${!opt} == [A-Za-z]* && ! ${LOG_LEVELS["${!opt,,}"]} ]]; then
 				[[ $opt == logLvl ]] &&
-					SCRIPT_OPTS[$opt]=${LOG_LEVELS[info]} ||
-					SCRIPT_OPTS[$opt]=${LOG_LEVELS[warn]}
-				log Warn ".$opt - unknown log level '${!opt}', defaulting to '${LOG_NAMES[${SCRIPT_OPTS[$opt]}]}'
+					SCRIPT_OPTS["$opt"]=${LOG_LEVELS[info]} ||
+					SCRIPT_OPTS["$opt"]=${LOG_LEVELS[warn]}
+				log Warn ".$opt - unknown log level '${!opt}', defaulting to '${LOG_NAMES[${SCRIPT_OPTS["$opt"]}]}'
   Available are: ${LOG_NAMES[*]}"
 			else
 				if [[ ${!opt} == -* ]]; then
-					((SCRIPT_OPTS[$opt] += ${!opt}))
+					((SCRIPT_OPTS["$opt"] += ${!opt}))
 				else
-					SCRIPT_OPTS[$opt]=${LOG_LEVELS[${!opt,}]:-${!opt}}
+					SCRIPT_OPTS["$opt"]=${LOG_LEVELS["${!opt,,}"]:-${!opt}}
 				fi
 			fi
-			unset "$opt" # to not parse logLvl twice (as opt and as arg)
 		fi
+		unset "$opt" # to not parse multiopt twice
 		i+=4
 	done
 	return 0
 }
 
-SCRIPT_OPTS[logLvl]=${DEBUG:-${SCRIPT_OPTS[logLvl]}}
 declare -A SSS_OPTS=( # internal behaviour / parsing options - script-specific edge case handling
 	[about]=''                             # script description
 	[exitFn]=exit                          # on error / on successful exit - shouldn't return
-	[exitLogLvl]=$((1 + SCRIPT_OPTS[cli])) # at which level to abort execution
+	[exitLogLvl]=$((1 + SCRIPT_OPTS[cli])) # at which level to abort (cli:Error, tui:Fatal)
 	# set to main registered action if script is a single command - actions act as builders
 	# you can also change other actions' params at runtime → dynamic configuration
 	# builder example: --builder init1 --builderOption --builder init2 'default action arg'
@@ -169,7 +191,7 @@ declare -A COLORS=(
 ansi() {
 	local ret code
 	while (($#)); do
-		[[ -z $1 || $1 == *[^a-z]* ]] && code= || code=${COLORS[$1]}
+		[[ -z $1 || $1 == *[^a-z]* ]] && code= || code=${COLORS["$1"]}
 		[[ $code ]] && ret+="[${code}m" || ret+=$1
 		shift
 	done
@@ -205,6 +227,10 @@ print() {
 				;;
 			[\'\"\`]*)
 				local delim=${str::1} _str=${str:1} str=${str:1}
+				if [[ -z $str ]]; then
+					ret+=$delim
+					continue
+				fi
 				hlStr=
 				while [[ -z $hlStr || ${str:${#hlStr}:1} == [a-zA-Z] ]]; do
 					hlStr+=${_str/${delim}*/$delim}
@@ -233,19 +259,21 @@ print() {
 #######################################
 # Print given message with context of current action and log level
 # Arguments:
-#   LAST_LOG_LVL: one of ${!LOG_LEVELS[@]}, determines message importance
+#   LAST_LOG_LVL: one of ${LOG_LEVELS[@]}, determines message importance
 #   msg: message to print with context, ignored when SCRIPT_OPTS[logLvl]<LAST_LOG_LVL
 # Returns:
 #   success or no return (calls exitFn)
 #######################################
 log() {
-	LAST_LOG_LVL=${LOG_LEVELS[${1,}]:-$1}
+	LAST_LOG_LVL=${LOG_LEVELS["${1,,}"]:-$1}
 	if ((SCRIPT_OPTS[logLvl] >= LAST_LOG_LVL)); then
 		local type=${LOG_NAMES[$LAST_LOG_LVL]}
 		((SCRIPT_OPTS[color] > 0)) && type=$(ansi "$type" "${type^^}" fg) || type=${type^^}
 		echo "$type$(print ": $ACTION$2")" 1>&2
 	fi
-	((SSS_OPTS[exitLogLvl] < LAST_LOG_LVL)) || "${SSS_OPTS[exitFn]}" 1
+	if ((SSS_OPTS[exitLogLvl] >= LAST_LOG_LVL)); then
+		[[ $ACTION == ${SSS_OPTS[exitFn]} ]] && exit -1 || "${SSS_OPTS[exitFn]}" $LAST_LOG_LVL
+	fi
 }
 
 # Supports simple redirection ... '>'/'>>' 'path'
@@ -321,8 +349,9 @@ parseAction() {
 			detectCase "${BASH_REMATCH[2]}" isAction
 		)
 	} || {
-		[[ $1 =~ ^-([^-])(.*)$ ]] && # short action
-			ACTION=${ACTION_INFO[${1:1:1}]} actionArg=${BASH_REMATCH[2]:+-${BASH_REMATCH[2]}}
+		[[ $1 =~ ^-([^-])(.*)$ ]] && { # short action
+			ACTION=${ACTION_INFO["${1:1:1}"]} actionArg=${BASH_REMATCH[2]:+-${BASH_REMATCH[2]}}
+		} && [[ $ACTION ]]
 	}; then # action recognized
 		if [[ $actionArg ]]; then
 			declare -i actionArgFromEnd=$#
@@ -389,6 +418,7 @@ parseAction() {
 					isOpt() { [[ ${opts["$1"]} ]]; }
 					detectCase "${tmpArr[3]}" isOpt
 				) && {
+					i=${opts["$i"]}
 					[[ ${tmpArr[2]} ]] && optCnt=- # `no-` means toggle off
 					[[ ! ${tmpArr[4]} ]] || local arg=${tmpArr[4]:1}
 				}
@@ -423,18 +453,23 @@ parseAction() {
 					else
 						shift
 					fi
-				elif [[ (! ${arg+y} || $optChain) &&
-					${SSS_OPTS[onNoArg]} == 0 && '' =~ ^$reg$ && 3 =~ ^$reg$ ]]; then
+				elif [[ (! ${arg+y} || $optChain) && ${SSS_OPTS[onNoArg]} -ge 0 ]] && argMatch; then
 					declare -i "$varName+=${optCnt}1"
 					log Debug ".$varName = ${!varName}"
-				elif [[ ! ${arg+y} && ${SCRIPT_OPTS[picker]} -gt 0 &&
-					(${SSS_OPTS[onNoArg]} -gt 0 || $optChain) ]] && {
+				elif [[ (! ${arg+y} || $optChain) && ${SSS_OPTS[onNoArg]} -gt 0 &&
+					${SCRIPT_OPTS[picker]} -gt 0 ]] && {
 
 					[[ ${sigs[i + 1]} == ?[+*] ]] && declare -a "$varName" || local "$varName"
 
-					"${builder[$varName]:=$(determinePicker "$reg")}" "${sigs[@]:i:4}"
+					"${builder["$varName"]:=$(determinePicker "$reg")}" "${sigs[@]:i:4}" || {
+						((${SCRIPT_OPTS[ignoreFailedPicker]} > 0)) && i=-1
+					}
 				}; then # picker picked a value successfully
-					log Debug ".$varName <${builder[$varName]}>= '${!varName}'"
+					if ((i < 0)); then
+						log Debug ".$varName - unchanged"
+					else
+						log Debug ".$varName <${builder["$varName"]}>= '${!varName}'"
+					fi
 				else # bad arg, or picker failed
 					[[ ! $optChain ]] &&
 						log Error ".$varName - Invalid argument '${arg-$1}' != /$reg/" ||
@@ -456,13 +491,21 @@ parseAction() {
 				posArg=$i
 			fi
 		else # set arg
-			((posArg < sigN)) || break
+			if ((posArg >= sigN)); then
+				if ((USE_ALL_ARGS)); then
+					log Error " - Too many arguments: $*"
+					return
+				else
+					break # NOTE: this is where the loop ends successfully
+				fi
+			fi
 			# remove '-' from arg incorrectly perceived as an option in a shortopt chain
 			[[ $# -eq $actionArgFromEnd && $1 ]] && set -- "${1#-}" "${@:2}"
 
 			while ((posArg < sigN)); do
 				local varName=${sigs[$posArg]//-/_} sign=${sigs[posArg + 1]} reg=${sigs[posArg + 2]}
 				if [[ $sign == \$? && $# -gt 0 ]] && argMatch "$1"; then
+					args[$posArg]+=1              # update before posArg changes
 					if [[ $sign == ?[+*] ]]; then # param is a list
 						declare _varName=$varName
 						declare -a "$varName"
@@ -475,7 +518,6 @@ parseAction() {
 						posArg+=4
 						log Debug "\$$varName = '${!varName}'"
 					fi
-					args[$posArg]+=1
 					shift
 					break # continue in parsing cli
 				else
@@ -498,9 +540,9 @@ parseAction() {
 		if [[ ${SCRIPT_OPTS[picker]} -gt 0 &&
 			(${SCRIPT_OPTS[optArgPicker]} -gt 0 || $sign == ?[+!]) ]]; then
 			declare -a "$varName"
-			if "${builder[$varName]:=$(determinePicker "$reg")}" "${sigs[@]:i:4}"; then
+			if "${builder["$varName"]:=$(determinePicker "$reg")}" "${sigs[@]:i:4}"; then
 				args[$i]+=1
-				log Debug "\$$varName <${builder[$varName]}>= '${!varName}'"
+				log Debug "\$$varName <${builder["$varName"]}>= '${!varName}'"
 			fi
 		fi
 
@@ -523,39 +565,55 @@ parseAction() {
 }
 
 call() { # for script usage - calling actions like itself with cli, without external process
-	parseAction "$@"
+	USE_ALL_ARGS=1 parseAction "$@"
 	(($? == $# && LAST_LOG_LVL > 3))
 }
 
 declare -A REGEX=(
-	[var]='[A-Za-z_][0-9A-Za-z_]+' [dashvar]='[A-Za-z_][0-9A-Za-z_\-]+'
-	[const]='[A-Z_][0-9A-Z_]+' [domain]='[a-z0-9]+\.[0-9a-z.]+'
+	[var]='[A-Za-z_][0-9A-Za-z_]*' [dashvar]='[A-Za-z_][0-9A-Za-z_\-]*'
+	[const]='[A-Z_][0-9A-Z_]*' [domain]='[a-z0-9]+\.[0-9a-z.]+'
 )
+REGEX[email]="${REGEX[var]}@${REGEX[domain]}"
 
 #######################################
 # Test if $reg matches $1, or the rest after parsing $reg == \$o.*; o = bash condexpr operator
 # example: reg='$f\.txt' → matches any existing file with 'txt' extension, '$F' for just filename
-# Arguments:
-#   tested: input argument to be tested against the pattern
+# Globals:
 #   reg: required format of the argument
+# Arguments:
+#   tested: input argument to be tested against the pattern (no arg to test for arg-less opt)
 #######################################
 argMatch() {
-	local toTest=$1 reg=${reg:-$2}
-	if [[ $reg == '$'* ]]; then
-		[[ $1 =~ ^[^-][^=]*$ ]] && {
+	local tested=$1
+	if (($# == 0)); then # if reg notation allows for parsing option as arg-less toggle
+		if [[ $reg == '$'* ]]; then
+			local reg=${reg:2}
+			reg=${reg#*\$|}
+			[[ ${#reg} -gt 0 && '' =~ ^$reg$ ]] # toggle (probably to tgl the file/opt use)
+		else
+			[[ '' =~ ^$reg$ ]] # toggle or counter
+		fi
+	elif [[ $reg == '$'* ]]; then # file requirements
+		[[ $tested =~ ^[^+-][^=]*$ ]] && {
 			if [[ ${reg:1:1} == [Ee] ]]; then # any dir or file with given pattern
-				[[ -d $1 ]] && return
+				[[ -d $tested ]] && return
 				[[ ${reg:1:1} == e ]] && reg="\$f${reg:2}" || reg="\$F${reg:2}"
 			fi
 
-			[[ $1 =~ ${reg:2}$ ]] && if [[ ${reg:1:1} == F ]]; then
-				[[ ! -d $toTest ]]
+			local ptn=${reg:2}
+			if [[ $ptn == *'$|'* ]]; then
+				[[ $tested =~ ^${ptn#*\$|}$ ]] && return # one of special values after '$|'
+				ptn=${ptn%\$|*}
+			fi
+
+			[[ $tested =~ $ptn$ ]] && if [[ ${reg:1:1} == F ]]; then
+				[[ ! -d $tested ]]
 			else
-				eval [[ -${reg:1:1} \$toTest ]]
+				eval [[ -${reg:1:1} \$tested ]]
 			fi
 		}
-	else
-		[[ $1 =~ ^$reg$ ]]
+	else # normal regex
+		[[ $tested =~ ^$reg$ ]]
 	fi
 }
 
@@ -652,7 +710,7 @@ help() {
 	((SCRIPT_OPTS[color] > 0)) && fmt='\033[1;4m%-*s   \033[0;4m%s\033[m' || fmt='%-*s   %s'
 	for act in "${actions[@]}"; do
 		if [[ ${act#-} == ? ]]; then
-			act=${ACTION_INFO[${act#-}]:-$act} # keep the original to have valid `desc` index
+			act=${ACTION_INFO["${act#-}"]:-$act} # keep the original to have valid `desc` index
 		elif [[ $act =~ ^-*([^-][^=]*)$ ]]; then
 			act=$(
 				isAction() { [[ ${ACTION_INFO["$1"]} ]]; }
@@ -704,10 +762,11 @@ pickValue() {
 			[[ $_pick ]] || break
 		done
 
-		if [[ $_pick && $2 == ?[+*] ]]; then
+		if [[ $2 == ?[+*] ]]; then
+			[[ $_pick ]] || break
 			_dst+=("$_pick")
 		else
-			_dst=$_pick
+			_dst="$_pick"
 			break
 		fi
 	done
@@ -715,7 +774,7 @@ pickValue() {
 }
 
 pickDir() {
-	local tmp=$(mktemp)
+	local tmp="$(mktemp)"
 	ranger --choosedir="$tmp"
 	if [[ -e $tmp ]]; then
 		declare -n _choice="$1"
@@ -726,7 +785,7 @@ pickDir() {
 }
 
 pickFile() {
-	local tmp=$(mktemp)
+	local tmp="$(mktemp)"
 	ranger --choosefile"$([[ $2 == ?[+*] ]] && echo s)=$tmp"
 	if [[ -e $tmp ]]; then
 		mapfile -t "$1" <"$tmp"
@@ -743,7 +802,7 @@ pickFilesOrDir() {
 		((SCRIPT_OPTS[guiPicker] > 0)) && _cmd+=(-multi-select) || _cmd+=(-m)
 	fi
 	declare -n selected="$1"
-	local toView=(.) _ng=$(shopt -p nullglob)
+	local toView=(.) _ng=("$(shopt -p nullglob)")
 	shopt -s nullglob
 	while :; do
 		local f
@@ -769,9 +828,11 @@ pickFilesOrDir() {
 		done
 		[[ ($selected && $2 != ?[+*]) || -z $toView ]] && break
 	done
-	"$_ng"
+	[[ ${_ng[1]} == -s ]] || shopt -u nullglob
 	[[ -e ${!1} ]]
 }
+
+config=1 define
 
 if [[ $0 == *sss ]]; then
 	SSS_OPTS[about]='SSS - A script simplifying scripting
@@ -791,4 +852,10 @@ Usage:
   9. Call `main "$@"` at the end of your script; set defAction for setup-then-exec use
 There are a few predefined pickers and regexes you can use.'
 	main "$@"
+	# style rules:
+	# - quote map indexing to avoid confusion with arrays (where text is expanded as a var)
+	# - use `&&/|| {...}` only for success value uses
+	# - use multiple `&&`, `||` in one cmd only when declaring variables
+	# - avoid `&&` where `;`/`\n` can be used when executing consecutive commands
+	# - use `[[...]] &&/||` to match the main intended path (→ `||` shows it's not the main intent)
 fi
