fix(mom): convert bitrate + better reform.nvim toggle use

diff --git a/bin/sss b/bin/sss
--- a/bin/sss
+++ b/bin/sss
@@ -27,24 +27,25 @@ actionInfo() {
 	ACTION_ORDER+=($name)
 }
 
-declare -Ai SSS_OPTS=( # helper + execution options - changeable by `define` action
+declare -A LOG_LEVELS=([quiet]=0 [error]=1 [warn]=2 [warning]=2 [info]=3 [verbose]=4 [debug]=5)
+LOG_NAMES=(quiet error warn info verbose debug)
+
+declare -Ai SCRIPT_OPTS=( # helper + runtime options - changeable by `define` action
 	[cli]=0          # user runs in CLI (1)
 	[tui]=0          # TUI mode should be run after parsing args/CLI
 	[picker]=0       # missing arguments can be picked through user input
 	[optArgPicker]=0 # optional arguments can be picked
 	[guiPicker]=0    # pickers prompt user with GUI (1) or use TUI (0)
 	[dryRun]=0       # fake external command execution (`exec` returns success)
-	[logLevel]=2     # current log level
+	[logLevel]=3     # current log level
 	[exitLogLvl]=2   # at which level to abort script execution and exit
 	# TODO: color option (for help display etc.)
 )
-[[ $# == 0 && -t 0 ]] && SSS_OPTS[tui]=1 SSS_OPTS[exitLogLvl]=1 || SSS_OPTS[cli]=1
-[[ -t 0 && -t 1 && -t 2 ]] && SSS_OPTS[picker]=1
-[[ -t 0 ]] || SSS_OPTS[guiPicker]=1
-declare -A LOG_LEVELS=([quiet]=0 [error]=1 [warn]=2 [warning]=2 [info]=3 [debug]=4)
-LOG_NAMES=(quiet error warn info debug)
+[[ $# == 0 && -t 0 ]] && SCRIPT_OPTS[tui]=1 SCRIPT_OPTS[exitLogLvl]=1 || SCRIPT_OPTS[cli]=1
+[[ -t 0 && -t 1 && -t 2 ]] && SCRIPT_OPTS[picker]=1
+[[ -t 0 ]] || SCRIPT_OPTS[guiPicker]=1
 
-declare -A SCRIPT_OPTS=( # behaviour + parsing options - script-specific edge case handling
+declare -A SSS_OPTS=( # internal behaviour / parsing options - script-specific edge case handling
 	[about]=      # script description
 	[exitFn]=exit # when all actions were executed; (commit/rollback) - should never return
 	# set to main registered action if script is a single command - actions act as builders
@@ -55,45 +56,46 @@ declare -A SCRIPT_OPTS=( # behaviour + parsing options - script-specific edge ca
 	[optPrefix]='-{,2}' # regex for required cli long name format
 	# [camelCase]=1       # whether to convert args to camelCase or snake_case
 	# TODO: option for disabling options after args (for better opt/act distinction)
+	# currently overcamable just by giving -- as arg (clears the options map so only args match)
 )
 
 #######################################
 # Print given message with context of current action and log level
 # Arguments:
 #   logLvl: one of ${!LOG_LEVELS[@]}, determines message importance
-#   msg: message to print with context, ignored when SSS_OPTS[logLevel]<logLvl
+#   msg: message to print with context, ignored when SCRIPT_OPTS[logLevel]<logLvl
 # Returns:
 #   success when message was printed, exits if Warning in cli mode or Error are reported
 #######################################
 log() {
 	logLvl=${LOG_LEVELS[${1,}]:-$1}
-	if ((SSS_OPTS[logLevel] >= logLvl)); then
+	if ((SCRIPT_OPTS[logLevel] >= logLvl)); then
 		local name=${LOG_NAMES[$logLvl]}
 		echo "${name^}: $action$2" 1>&2
 	fi
-	((logLvl > ${SSS_OPTS[exitLogLvl]})) || ${SCRIPT_OPTS[exitFn]} 1
-	((SSS_OPTS[logLevel] >= logLvl))
+	((logLvl > ${SCRIPT_OPTS[exitLogLvl]})) || ${SSS_OPTS[exitFn]} 1
+	((SCRIPT_OPTS[logLevel] >= logLvl))
 }
 
 exec() {
-	((SSS_OPTS[logLevel] > 2)) && log Info "\$> $*"
-	((SSS_OPTS[dryRun])) && return 0
+	((SCRIPT_OPTS[logLevel] > 3)) && log Verbose "\$> $*"
+	((SCRIPT_OPTS[dryRun])) && return 0
 	[[ ${!#} == \& ]] && { "${@:1:$((${#} - 1))}" & } || "$@"
 }
 
 main() {
-	if ((SSS_OPTS[cli])); then
+	if ((SCRIPT_OPTS[cli])); then
 		while (($#)); do
 			parseAction "$@"
 			shift $?
 		done
-		((SSS_OPTS[tui])) || quit
-		SSS_OPTS[cli]=0
+		((SCRIPT_OPTS[tui])) || quit
+		SCRIPT_OPTS[cli]=0
 	fi
 
-	SSS_OPTS[picker]=1
+	SCRIPT_OPTS[picker]=1
 	while :; do
-		if ((SSS_OPTS[optArgPicker])); then
+		if ((SCRIPT_OPTS[optArgPicker])); then
 			read -rp 'Choose action (+opts): ' line
 		else
 			read -rp 'Choose action: ' -n 1 line
@@ -103,7 +105,7 @@ main() {
 			parseAction -$line
 		else
 			local _prefix=
-			while [[ ! $_prefix =~ ^${SCRIPT_OPTS[optPrefix]}$ ]]; do
+			while [[ ! $_prefix =~ ^${SSS_OPTS[optPrefix]}$ ]]; do
 				_prefix+=-
 			done
 			parseAction $_prefix$line
@@ -117,7 +119,7 @@ parseAction() {
 	declare -i argc=$#
 	# get action name
 	local action=''
-	if [[ $1 =~ ^(${SCRIPT_OPTS[optPrefix]})([^-][^=]+)(=.*)?$ ]]; then
+	if [[ $1 =~ ^(${SSS_OPTS[optPrefix]})([^-][^=]+)(=.*)?$ ]]; then
 		local action=$(argToCase "${BASH_REMATCH[2]}") actionArg=${BASH_REMATCH[3]:1}
 		[[ ${ACTION_INFO["$action"]} ]] || action='' actionArg=''
 	fi
@@ -127,7 +129,7 @@ parseAction() {
 	if [[ $action ]]; then
 		[[ $actionArg ]] && set -- "$actionArg" || shift
 	else
-		action=${SCRIPT_OPTS[defAction]} actionArg=
+		action=${SSS_OPTS[defAction]} actionArg=
 	fi
 
 	declare -n sigs=${action}Params
@@ -157,9 +159,9 @@ parseAction() {
 	declare -n builder=${action}Builder
 	while [[ $1 ]]; do # get options and args
 		# parse option prefix
-		[[ $1 == -- && ${#ids[@]} -gt 0 ]] && shift && ids=() && continue
+		[[ $1 == -- && ${#ids[@]} -gt 0 ]] && shift && ids=() && continue # only args will be found
 		local i= arg= optCnt=+
-		if [[ $1 =~ ^(${SCRIPT_OPTS[optPrefix]})(no-|NO_)?([^- ][^= ]+)(=.+)?$ && -z $actionArg ]]; then
+		if [[ $1 =~ ^(${SSS_OPTS[optPrefix]})(no-|NO_)?([^- ][^= ]+)(=.+)?$ && -z $actionArg ]]; then
 			i=${ids["$(argToCase ${BASH_REMATCH[3]})"]} # full option name
 			[[ $i ]] && arg=${BASH_REMATCH[4]:1}
 			[[ ${BASH_REMATCH[2]} ]] && optCnt=-
@@ -196,7 +198,7 @@ parseAction() {
 				elif [[ -z $arg && '' =~ ^$reg$ ]]; then # no arg, allows '' → number of uses as value
 					declare -i $varName+=${optCnt}1
 				else
-					if ((SSS_OPTS[picker])) && [[ -z $arg && ${sigs[i + 1]} != ?[+!] ]]; then
+					if ((SCRIPT_OPTS[picker])) && [[ -z $arg && ${sigs[i + 1]} != ?[+!] ]]; then
 						declare -a $varName # picker for options
 						log Debug ".$varName << ${builder[$varName]:-pickAny}"
 						${builder[$varName]:-pickAny} "${sigs[@]:i:4}"
@@ -234,8 +236,8 @@ $(paramHelp $action $((i / 4)))" && return
 					log Debug ".arg.$varName = '${!varName}'"
 					break # continue in parsing cli
 				elif [[ ! ${!varName} ]]; then
-					if ((SSS_OPTS[picker])); then # picker for optional args || arg required
-						if ((SSS_OPTS[optArgPicker])) || [[ $sign == *[+!] ]]; then
+					if ((SCRIPT_OPTS[picker])); then # picker for optional args || arg required
+						if ((SCRIPT_OPTS[optArgPicker])) || [[ $sign == *[+!] ]]; then
 							log Debug ".arg.$varName = <${builder[$varName]:-pickAny}>"
 							declare -a $varName # prepare variable as local
 							${builder[$varName]:-pickAny} "${sigs[@]:posArg:4}"
@@ -245,8 +247,8 @@ $(paramHelp $action $((i / 4)))" && return
 						if [[ $sign == [?*] ]]; then
 							((posArg += 4))
 						else
-							log Error " - Argument expected:
-$(paramHelp $action $((posArg / 4)))" && return
+							log Error " - Argument missing or incorrect:
+$(matcher=1 paramHelp $action $((posArg / 4)))" && return
 						fi
 					else
 						break
@@ -264,8 +266,8 @@ $(paramHelp $action $((posArg / 4)))" && return
 		local varName=${sigs[$i]} sign=${sigs[i + 1]} reg=${sigs[i + 2]}
 		[[ $sign == ?[?*] ]] && continue # option between arguments
 		if [[ ! ${!varName} ]]; then
-			if ((SSS_OPTS[picker])); then # picker for optional args || arg required
-				if ((SSS_OPTS[optArgPicker])) || [[ $sign == *[+!] ]]; then
+			if ((SCRIPT_OPTS[picker])); then # picker for optional args || arg required
+				if ((SCRIPT_OPTS[optArgPicker])) || [[ $sign == *[+!] ]]; then
 					log Debug ".$varName = <${builder[$varName]:-pickAny}>"
 					declare -a $varName # prepare variable as local
 					${builder[$varName]:-pickAny} "${sigs[@]:i:4}"
@@ -280,8 +282,8 @@ $(paramHelp $action $((i / 4)))" && return
 	unset ids arg posArg firstArg args builder varName sign reg
 
 	# ensure valid state
-	if [[ $action == "${SCRIPT_OPTS[defAction]}" &&
-		$# -gt 0 && ! ${SCRIPT_OPTS[defActionRep]} ]]; then
+	if [[ $action == "${SSS_OPTS[defAction]}" &&
+		$# -gt 0 && ! ${SSS_OPTS[defActionRep]} ]]; then
 		log Error " - Default action must be used last, but was followed by: $*"
 	fi
 	[[ $actionArg && $# -eq 1 ]] && log Error " - Unexpected argument '$actionArg'" && return
@@ -289,7 +291,7 @@ $(paramHelp $action $((i / 4)))" && return
 	# cleanup and action call
 	declare +n sigs
 	unset sigs i sigN
-	$action || log Warning ' failed!'
+	$action || log Warn ' failed!'
 	[[ $actionArg ]] && return 1 || return $((argc - $#))
 }
 
@@ -330,7 +332,7 @@ argMatch() {
 }
 
 argToCase() {
-	# ((${SCRIPT_OPTS[camelCase]})) || { echo "${1//-/_}" && return 0; }
+	# ((${SSS_OPTS[camelCase]})) || { echo "${1//-/_}" && return 0; }
 	[[ $1 == *-* ]] || { echo "$1" && return 0; }
 
 	local str=${1#*-}
@@ -344,7 +346,7 @@ argToCase() {
 	echo "$ret${str^}"
 }
 caseToArg() {
-	# ((${SCRIPT_OPTS[camelCase]})) || { echo "${1//_/-}" && return 0; }
+	# ((${SSS_OPTS[camelCase]})) || { echo "${1//_/-}" && return 0; }
 	[[ $1 == *[A-Z]* ]] || { echo "$1" && return 0; }
 
 	local str=$1
@@ -376,14 +378,14 @@ define() {
 	local opt
 	while [[ -z ${defineParams[i + 2]} ]]; do
 		opt=${defineParams[i]}
-		((${!opt})) && SSS_OPTS[$opt]=${!opt%-*}
+		((${!opt})) && SCRIPT_OPTS[$opt]=${!opt%-*}
 		i+=4
 	done
 	while [[ ${defineParams[i]} ]]; do
 		opt=${defineParams[i]}
 		if [[ ${!opt} ]]; then
-			[[ ${!opt} == -* ]] && ((SSS_OPTS[$opt] += ${!opt})) ||
-				SSS_OPTS[$opt]=${LOG_LEVELS[${!opt,}]:-${!opt}}
+			[[ ${!opt} == -* ]] && ((SCRIPT_OPTS[$opt] += ${!opt})) ||
+				SCRIPT_OPTS[$opt]=${LOG_LEVELS[${!opt,}]:-${!opt}}
 			unset $opt
 		fi
 		i+=4
@@ -394,7 +396,7 @@ define() {
 #######################################
 # Print help about specified parameter from given action.
 # Globals:
-#   matcher: boolean
+#   matcher: boolean show regex used for matching args
 # Arguments:
 #   action: string
 #   paramIdx?: integer
@@ -444,7 +446,7 @@ help() {
 	if [[ ! $actions ]]; then
 		declare -n actions=ACTION_ORDER
 		local default=true
-		((SSS_OPTS[cli])) && echo "${SCRIPT_OPTS[about]}"
+		((SCRIPT_OPTS[cli])) && echo "${SSS_OPTS[about]}"
 	fi
 	((legend > 0)) && echo 'Legend:
   action: [a]ction
@@ -452,7 +454,7 @@ help() {
       - prefix with `-`
       - value immediately after or as the next arg (-aVal / -a val)
     - full name usage: can help distinguish next action from previous opts
-      - prefix must match /'"${SCRIPT_OPTS[optPrefix]}"'/
+      - prefix must match /'"${SSS_OPTS[optPrefix]}"'/
       - value given with `=` or as the next arg (--act=val / --act val)
     - orderless (aside of repeated uses)
   options/named params: option[o] + suffix ?*!+
@@ -490,7 +492,7 @@ help() {
 
 actionInfo quit 'exit the tui' # also called when exiting the cli
 quit() {
-	${SCRIPT_OPTS[exitFn]} 0 # override this for commit-before-exit
+	${SSS_OPTS[exitFn]} 0 # override this for commit-before-exit
 }
 
 unknownParams=(received '+' '.*' 'consumes all remaining args to end execution')
@@ -514,7 +516,7 @@ pickAny() {
 	while :; do
 		local _pick=
 		while [[ ! $_pick =~ ^$3$ ]]; do
-			if ((${SSS_OPTS[guiPicker]} > 0)); then
+			if ((${SCRIPT_OPTS[guiPicker]} > 0)); then
 				_pick=$(rofi -dmenu -p "${_pick:+Argument has to match /$3/! }$4")
 			else
 				[[ $_pick ]] && echo "Argument has to match /$3/"
@@ -578,10 +580,10 @@ pickFilesOrDir() {
 }
 
 if [[ $0 == *sss ]]; then
-	SCRIPT_OPTS[about]='SSS - A script simplifying scripting
+	SSS_OPTS[about]='SSS - A script simplifying scripting
 Provides automatized param handling, arg/opt parsing+autodoc.
 Usage:
-  1. Change SCRIPT_OPTS to suit your script.
+  1. Change SSS_OPTS to suit your script.
   2. Source this script: `. sss`
   3. Register your actions
     `actionInfo <fName> <shortName>? <shortHighlight>? <fDescription>`
@@ -591,7 +593,7 @@ Usage:
     `declare -A <fName>Builder=([<argName>]=<picker/selector fName>)`
   6. Picker gets full arg quaternion, saves selection to $1/argName
   7. Write your function.
-  8?. for execution after configuration overwrite SCRIPT_OPTS[exitFn]
+  8?. for execution after configuration overwrite SSS_OPTS[exitFn]
   9. Call `main "$@"` at the end of your script; set defAction for setup-then-exec use
 There are a few predefined pickers and regexes you can use.'
 	main "$@"
